### ISSUE TITLE
KeyError: 'datastore_v3'

### ISSUE THREAD

**Issue by fredrikbonander** [jgeewax/gaetestbed#8]
When trying to run geatestbed in JetBrains PyCharm my test fails with an exception KeyError: 'datastore_v3'. While running it from command-line with "nosetests --with-gae" it works. Don't know if the bug is in geatestbed or PyCharm. Also reported it on jetbrains issue tracker: 

http://youtrack.jetbrains.net/issue/PY-2400?projectKey=PY

**Comment by jgeewax** [comment]
I just recently had issues with a KeyError with 'taskqueue' and tried the following:

```
$ sudo easy_install -U NoseGAE
```

Can you give that a try and see if it works?

**Comment by fredrikbonander** [comment]
Unfortunately I already had the newest version. And tried to installing it again, but still have the same issue :/
